
azure:
  connect_str: 'DefaultEndpointsProtocol=https;AccountName=v12daily;AccountKey=2tBxBHZwM5WNyzPAyozRtsircGCFBAMN2S3TfZGFN923bIlkWAjdn5scM5vV5TkYPFKvukfD/cL5+AStMluGag==;EndpointSuffix=core.windows.net'
  container_name: 'gcsteamcont'
  blob_name: 'test_to_gcsteamcont'


indexes:
  states: 'press-state-history*'
  restarts: 'restarts*'
  swv: 'sw-versions*'
  substrates: 'substrate-properties-*'
  prints: 'print-attempt*, print-session*'
  events: 'event-history*'

